In [3]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_excel("order.xlsx")
df.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [15]:
df.shape

(9994, 16)

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order Id          9994 non-null   int64
 1   Order Date        9994 non-null   datetime64[us]
 2   Ship Mode         9993 non-null   str
 3   Segment           9994 non-null   str
 4   Country           9994 non-null   str
 5   City              9994 non-null   str
 6   State             9994 non-null   str
 7   Postal Code       9994 non-null   int64
 8   Region            9994 non-null   str
 9   Category          9994 non-null   str
 10  Sub Category      9994 non-null   str
 11  Product Id        9994 non-null   str
 12  cost price        9994 non-null   int64
 13  List Price        9994 non-null   int64
 14  Quantity          9994 non-null   int64
 15  Discount Percent  9994 non-null   int64
dtypes: datetime64[us](1), int64(6), str(9)
memory usage: 1.2 MB

In [17]:
df.describe()

,Order Id,Order Date,Postal Code,cost price,List Price,Quantity,Discount Percent
count,9994.000000,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2022-12-29 10:20:34.820892,55190.379428,201.189714,229.756854,3.789574,3.484090
min,1.000000,2022-01-01 00:00:00,1040.000000,0.000000,0.000000,1.000000,2.000000
25%,2499.250000,2022-06-29 00:00:00,23223.000000,20.000000,20.000000,2.000000,2.000000
50%,4997.500000,2022-12-28 00:00:00,56430.500000,50.000000,50.000000,3.000000,3.000000
75%,7495.750000,2023-07-03 00:00:00,90008.000000,180.000000,210.000000,5.000000,4.000000
max,9994.000000,2023-12-31 00:00:00,99301.000000,18110.000000,22640.000000,14.000000,5.000000
std,2885.163629,NaN,32063.693350,537.743203,623.245839,2.225110,1.114211

In [19]:
df.dtypes

Order Id                     int64
Order Date          datetime64[us]
Ship Mode                      str
Segment                        str
Country                        str
City                           str
State                          str
Postal Code                  int64
Region                         str
Category                       str
Sub Category                   str
Product Id                     str
cost price                   int64
List Price                   int64
Quantity                     int64
Discount Percent             int64
dtype: object

In [4]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.columns.tolist()

['Order Id',
 'Order Date',
 'Ship Mode',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Category',
 'Sub Category',
 'Product Id',
 'cost price',
 'List Price',
 'Quantity',
 'Discount Percent',
 'Discount Amount']

In [8]:
discount_amount = (df['List Price'] * df['Discount Percent'])/100

In [9]:
discount_amount.head()

0     5.2
1    21.9
2     0.5
3    19.2
4     1.0
dtype: float64

In [10]:
df['Discount Amount'] = discount_amount

In [41]:
df.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent,Discount,Sales Price,Discount Amount
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,5.2,5.2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,21.9,21.9
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,0.5,0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,19.2,19.2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,1.0,1.0

In [45]:
df.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent', 'Discount Amount'],
      dtype='str')

In [11]:
df['Selling Price'] = df['List Price'] - df['Discount Amount']

In [12]:
df['Profit'] = (df['Selling Price'] - df['cost price']) * df['Quantity']

In [52]:
df.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent,Discount Amount,Selling Price,Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,29.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,324.3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-1.0
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,804.0
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-2.0

In [53]:
df['Profit'].sum()

np.float64(1039928.2)

In [58]:
df.groupby('Category')['Profit'].sum().sort_values(ascending=False)

Category
Technology         379720.7
Furniture          342782.4
Office Supplies    317425.1
Name: Profit, dtype: float64

In [61]:
df.groupby('Product Id')['Profit'].sum().sort_values(ascending=False).head(10)

Product Id
TEC-CO-10004722    24816.0
TEC-MA-10002412    21746.4
OFF-BI-10000545    17867.7
TEC-CO-10001449    15948.0
FUR-CH-10002024    13930.7
OFF-BI-10003527    12792.9
TEC-PH-10001459    11481.9
TEC-MA-10000822    10102.3
FUR-TA-10000198    10015.1
TEC-MA-10001047     9989.0
Name: Profit, dtype: float64

In [62]:
df.groupby('City')['Profit'].sum().sort_values(ascending=False).head(10)

City
New York City    103852.6
Los Angeles       73294.8
Philadelphia      52619.3
Seattle           50765.7
San Francisco     48472.6
Jacksonville      29560.5
Houston           27982.9
Detroit           24813.1
San Diego         21398.4
Springfield       20499.1
Name: Profit, dtype: float64

In [63]:
df.groupby('Region')['Profit'].sum().sort_values(ascending=False)

Region
West       305289.6
East       295773.8
Central    236121.2
South      202743.6
Name: Profit, dtype: float64

In [65]:
df.groupby('Segment')['Profit'].sum().sort_values(ascending=False)

Segment
Consumer       514980.1
Corporate      330596.1
Home Office    194352.0
Name: Profit, dtype: float64

In [68]:
df.groupby('Category')['Discount Percent'].mean().sort_values(ascending=False)

Category
Technology         3.496481
Furniture          3.489863
Office Supplies    3.478261
Name: Discount Percent, dtype: float64

In [74]:
df.groupby('Sub Category')['Profit'].sum().sort_values(ascending=False).head(5)

Sub Category
Chairs     153905.7
Phones     139498.5
Binders     98802.8
Tables      98522.2
Storage     96105.3
Name: Profit, dtype: float64

In [14]:
df.to_csv("orders.csv", index = False)

In [13]:
df.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent', 'Discount Amount', 'Selling Price', 'Profit'],
      dtype='str')