In [4]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_excel("telco.xlsx")
df.head()

,Customer ID,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents,Country,State,...,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Customer Status,Churn Label,Churn Score,CLTV,Churn Category,Churn Reason
0,8779-QRDMV,Male,78,No,Yes,No,No,0,United States,California,...,20,0.00,59.65,3,Churned,Yes,91,5433,Competitor,Competitor offered more data
1,7495-OOKFY,Female,74,No,Yes,Yes,Yes,1,United States,California,...,0,390.80,1024.10,3,Churned,Yes,69,5302,Competitor,Competitor made better offer
2,1658-BYGOY,Male,71,No,Yes,No,Yes,3,United States,California,...,0,203.94,1910.88,2,Churned,Yes,81,3179,Competitor,Competitor made better offer
3,4598-XLKNJ,Female,78,No,Yes,Yes,Yes,1,United States,California,...,0,494.00,2995.07,2,Churned,Yes,88,5337,Dissatisfaction,Limited range of services
4,4846-WHAFZ,Female,80,No,Yes,Yes,Yes,1,United States,California,...,0,234.21,3102.36,2,Churned,Yes,67,2793,Price,Extra data charges

In [8]:
df.shape

(7043, 50)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 50 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer ID                        7043 non-null   str
 1   Gender                             7043 non-null   str
 2   Age                                7043 non-null   int64
 3   Under 30                           7043 non-null   str
 4   Senior Citizen                     7043 non-null   str
 5   Married                            7043 non-null   str
 6   Dependents                         7043 non-null   str
 7   Number of Dependents               7043 non-null   int64
 8   Country                            7043 non-null   str
 9   State                              7043 non-null   str
 10  City                               7043 non-null   str
 11  Zip Code                           7043 non-null   int64
 12  Latitude                           7043 non-null   float64
 13  Longitude                          7043 non-null   float64
 14  Population                         7043 non-null   int64
 15  Quarter                            7043 non-null   str
 16  Referred a Friend                  7043 non-null   str
 17  Number of Referrals                7043 non-null   int64
 18  Tenure in Months                   7043 non-null   int64
 19  Offer                              3166 non-null   str
 20  Phone Service                      7043 non-null   str
 21  Avg Monthly Long Distance Charges  7043 non-null   float64
 22  Multiple Lines                     7043 non-null   str
 23  Internet Service                   7043 non-null   str
 24  Internet Type                      5517 non-null   str
 25  Avg Monthly GB Download            7043 non-null   int64
 26  Online Security                    7043 non-null   str
 27  Online Backup                      7043 non-null   str
 28  Device Protection Plan             7043 non-null   str
 29  Premium Tech Support               7043 non-null   str
 30  Streaming TV                       7043 non-null   str
 31  Streaming Movies                   7043 non-null   str
 32  Streaming Music                    7043 non-null   str
 33  Unlimited Data                     7043 non-null   str
 34  Contract                           7043 non-null   str
 35  Paperless Billing                  7043 non-null   str
 36  Payment Method                     7043 non-null   str
 37  Monthly Charge                     7043 non-null   float64
 38  Total Charges                      7043 non-null   float64
 39  Total Refunds                      7043 non-null   float64
 40  Total Extra Data Charges           7043 non-null   int64
 41  Total Long Distance Charges        7043 non-null   float64
 42  Total Revenue                      7043 non-null   float64
 43  Satisfaction Score                 7043 non-null   int64
 44  Customer Status                    7043 non-null   str
 45  Churn Label                        7043 non-null   str
 46  Churn Score                        7043 non-null   int64
 47  CLTV                               7043 non-null   int64
 48  Churn Category                     1869 non-null   str
 49  Churn Reason                       1869 non-null   str
dtypes: float64(8), int64(11), str(31)
memory usage: 2.7 MB

In [11]:
df.nunique()

Customer ID                          7043
Gender                                  2
Age                                    62
Under 30                                2
Senior Citizen                          2
Married                                 2
Dependents                              2
Number of Dependents                   10
Country                                 1
State                                   1
City                                 1106
Zip Code                             1626
Latitude                             1626
Longitude                            1625
Population                           1569
Quarter                                 1
Referred a Friend                       2
Number of Referrals                    12
Tenure in Months                       72
Offer                                   5
Phone Service                           2
Avg Monthly Long Distance Charges    3584
Multiple Lines                          2
Internet Service                        2
Internet Type                           3
Avg Monthly GB Download                50
Online Security                         2
Online Backup                           2
Device Protection Plan                  2
Premium Tech Support                    2
Streaming TV                            2
Streaming Movies                        2
Streaming Music                         2
Unlimited Data                          2
Contract                                3
Paperless Billing                       2
Payment Method                          3
Monthly Charge                       1585
Total Charges                        6540
Total Refunds                         500
Total Extra Data Charges               16
Total Long Distance Charges          6068
Total Revenue                        6975
Satisfaction Score                      5
Customer Status                         3
Churn Label                             2
Churn Score                            81
CLTV                                 3438
Churn Category                          5
Churn Reason                           20
dtype: int64

In [12]:
df.isnull().sum().sort_values(ascending = False)

Churn Reason                         5174
Churn Category                       5174
Offer                                3877
Internet Type                        1526
Senior Citizen                          0
Married                                 0
Age                                     0
Under 30                                0
Country                                 0
State                                   0
City                                    0
Zip Code                                0
Latitude                                0
Longitude                               0
Dependents                              0
Number of Dependents                    0
Customer ID                             0
Gender                                  0
Number of Referrals                     0
Referred a Friend                       0
Quarter                                 0
Population                              0
Avg Monthly Long Distance Charges       0
Multiple Lines                          0
Phone Service                           0
Tenure in Months                        0
Online Security                         0
Online Backup                           0
Device Protection Plan                  0
Premium Tech Support                    0
Streaming TV                            0
Streaming Movies                        0
Internet Service                        0
Avg Monthly GB Download                 0
Unlimited Data                          0
Streaming Music                         0
Contract                                0
Paperless Billing                       0
Total Charges                           0
Total Refunds                           0
Payment Method                          0
Monthly Charge                          0
Total Long Distance Charges             0
Total Extra Data Charges                0
Total Revenue                           0
Satisfaction Score                      0
Churn Label                             0
Customer Status                         0
CLTV                                    0
Churn Score                             0
dtype: int64

In [14]:
pd.crosstab(df['Customer Status'], df['Churn Reason'], dropna = False)

Churn Reason,Attitude of service provider,Attitude of support person,Competitor had better devices,Competitor made better offer,Competitor offered higher download speeds,Competitor offered more data,Deceased,Don't know,Extra data charges,Lack of affordable download/upload speed,...,Limited range of services,Long distance charges,Moved,Network reliability,Poor expertise of online support,Poor expertise of phone support,Price too high,Product dissatisfaction,Service dissatisfaction,NaN
Customer Status,,,,,,,,,,,,,,,,,,,,,
Churned,94,220,313,311,100,117,6,130,39,30,...,37,64,46,72,31,12,78,77,63,0
Joined,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,454
Stayed,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4720

In [15]:
pd.crosstab(df['Customer Status'], df['Churn Category'], dropna = False)

Churn Category   Attitude  Competitor  Dissatisfaction  Other  Price   NaN
Customer Status
Churned               314         841              303    200    211     0
Joined                  0           0                0      0      0   454
Stayed                  0           0                0      0      0  4720

In [16]:
pd.crosstab(df['Customer Status'], df['Offer'], dropna = False)

Offer            Offer A  Offer B  Offer C  Offer D  Offer E   NaN
Customer Status
Churned               35      101       95      161      426  1051
Joined                 0        0        0        0      175   279
Stayed               485      723      320      441      204  2547

In [5]:
[col for col in df.columns if 'Charge' in col]

['Avg Monthly Long Distance Charges',
 'Monthly Charge',
 'Total Charges',
 'Total Extra Data Charges',
 'Total Long Distance Charges']

In [6]:
[col for col in df.columns if 'Revenue' in col]

['Total Revenue']

In [7]:
[col for col in df.columns if 'CLTV' in col]

['CLTV']

In [22]:
df.duplicated("Customer ID").sum()

np.int64(0)

In [24]:
pd.crosstab(df["Customer ID"], df["Internet Type"], dropna = False)

Internet Type  Cable  DSL  Fiber Optic  NaN
Customer ID
0002-ORFBO         1    0            0    0
0003-MKNFE         1    0            0    0
0004-TLHLJ         0    0            1    0
0011-IGKFF         0    0            1    0
0013-EXCHZ         0    0            1    0
...              ...  ...          ...  ...
9987-LUTYD         0    1            0    0
9992-RRAMN         0    0            1    0
9992-UJOEL         0    1            0    0
9993-LHIEB         1    0            0    0
9995-HOTOH         1    0            0    0

[7043 rows x 4 columns]

In [25]:
pd.crosstab(df["Customer ID"], df["Internet Service"], dropna = False)

Internet Service  No  Yes
Customer ID
0002-ORFBO         0    1
0003-MKNFE         0    1
0004-TLHLJ         0    1
0011-IGKFF         0    1
0013-EXCHZ         0    1
...               ..  ...
9987-LUTYD         0    1
9992-RRAMN         0    1
9992-UJOEL         0    1
9993-LHIEB         0    1
9995-HOTOH         0    1

[7043 rows x 2 columns]